name: Build and Deploy
on:
  push:
    branches:
      - main  # 或者你的默认分支名
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 这一行很重要，添加写权限
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.23.2'
          
      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          commit_message: 'deploy: update site'
